books/urls.py
from django.urls import path

from books.views import AddComment, BookList, BookDetail, Search

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="home"),
    path("search/", Search.as_view(), name="search"),
    path("<slug:slug>/", BookDetail.as_view(), name="detail"),
    path("add/<slug:slug>/", AddComment.as_view(), name="add_comment"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("registration/", include("registration.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include('social_django.urls', namespace='social')),
    path("", include("books.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path

from registration.views import signin_view, signup_view, logout_view

app_name = "registration"

urlpatterns = [
    path("signin/", signin_view, name="signin"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
]

books/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    """
    Model `Author` for model `Book`
    """

    full_name = models.CharField(max_length=150)

    def __str__(self):
        return str(self.full_name)


class Genre(models.Model):
    """
    Model `Category` for model `Book`
    """

    genre = models.CharField(max_length=150)

    def __str__(self):
        return str(self.genre)


class Book(models.Model):
    """
    Book model
    """

    title = models.CharField(max_length=150)
    slug = models.SlugField(unique_for_date="publish_date")
    body = models.TextField()
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    pdf = models.FileField(upload_to="books/", blank=True, null=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    class Meta:
        ordering = ("-publish_date",)

    def __str__(self):
        return f"Book({self.title}, {self.publish_date}, {self.status})"

    def get_absolute_url(self):
        return reverse("books:detail", args=[str(self.slug)])


class Comment(models.Model):
    """
    Model `Comment` for model `Book`
    """

    username = models.CharField(max_length=150)
    body = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("-publish_date",)

    def __str__(self):
        return f"Comment({self.username}, {self.body}, {self.publish_date})"

books/forms.py
from django import forms

from ckeditor_uploader.widgets import CKEditorUploadingWidget

from books.models import Book, Comment


class CommentForm(forms.ModelForm):
    """Comment form"""

    class Meta:
        model = Comment
        fields = ("username", "body")


class BooktAdminForm(forms.ModelForm):
    """CKEditor form for the `body` field of the `Book` model"""

    body = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Book
        fields = "__all__"

books/views.py
from django.contrib.postgres.search import SearchVector
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View

from books.forms import CommentForm
from books.models import Book


class BookList(View):
    """List all book"""

    def get(self, request):
        obj_list = Book.objects.filter(status=True)

        paginator = Paginator(obj_list, 6)
        page = request.GET.get("page")

        try:
            books = paginator.page(page)
        except PageNotAnInteger:
            books = paginator.page(1)
        except EmptyPage:
            books = paginator.page(paginator.num_pages)

        context = {"books": books}
        return render(request, "books/home.html", context)


class BookDetail(View):
    """Retrieve a book instance"""

    def get(self, request, slug: str):
        book = get_object_or_404(Book, slug=slug)
        comments = book.comment_set.filter(active=True)
        context = {"book": book, "comments": comments}
        return render(request, "books/detail.html", context)


class AddComment(LoginRequiredMixin, View):
    """Add comment"""

    def post(self, request, slug: str):
        book = get_object_or_404(Book, slug=slug)
        form = CommentForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.book = book
            form.save()

        return redirect(book.get_absolute_url())


class Search(View):
    """Search"""

    def get(self, request):
        q = request.GET.get("q")

        books = Book.objects.annotate(
            search=SearchVector("title", "author__full_name")
        ).filter(search=q)

        context = {"books": books, "q": q}
        return render(request, "books/home.html", context)

templates/books/detail.html
{% extends "index.html" %}

{% block content %}
  <div class="container mt-4">

	<!-- info about book -->
      <div class="container">
          <p class="mb-0">{{ book.body|safe }}</p>
      </div>
    </div>

	<br>
	<br>

	<!-- comment form -->
	{% if request.user.is_authenticated %}
    <div class="row mt-3">
      <div class="col-md-12">
				<form action="{% url 'books:add_comment' book.slug %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="exampleInputUsername">Username</label>
						<input name="username" type="text" class="form-text text-muted also-bg" id="exampleInputUsername" placeholder="Enter username">
					</div>
					<div class="form-group">
						<label for="exampleInputComment">Comment</label>
						<p>
							<textarea class="also-bg color-text" name="body" id="exampleInputComment" cols="115" rows="5"></textarea>
						</p>
						<button class="btn btn-outline-light" type="submit">Add comment <i class="bi bi-send-fill"></i></button>
					</div>
        </form>
      </div>
    </div>
		{% else %}
			<div class="card also-bg">
				<div class="card-title text-center">
					Comments can only be left by authenticated users.
				</div>
			</div>
		{% endif %}

		<!-- list comments -->
		{% for comment in comments %}
		<div class="card border border-white also-bg">
			<div class="card-body">
				<h5 class="card-title">{{ comment.username }}</h5>
				<p class="card-text">{{ comment.body }}</p>
				<p class="card-text"><small class="text-muted">{{ comment.publish_date }}</small></p>
			</div>
		</div>
		{% endfor %}
  </div>
{% endblock content %}

templates/books/home.html
{% extends "index.html" %}

{% block content %}
<!-- books cards -->
{% if books %}
	<div class="row">
		{% for book in books %}
			<div class="col-12 col-md-4">
				<div class="card also-bg">
					<img src="{{ book.image.url }}" alt="{{ book.title }}" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h5>
						<div class="card-footer">
							<small class="text-muted">Publish {{ book.publish_date }} by {{ book.author }}</small>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>

	<br>
	<!-- paginator -->
	{% include "included/paginator.html" %}

<!-- if not books -->
{% else %}
	{% if q %}
		<h1 class="text-center"><strong>No books found for "{{ q }}"</strong></h1>
	{% else %}
		<h1 class="text-center"><strong>No books found</strong></h1>
	{% endif %}
{% endif %}

{% endblock content %}

templates/included/navbar.html
<nav class="navbar navbar-dark nav-bg"
	<div class="d-flex">
		<a class="navbar-brand mr-auto p-2" href="{% url 'books:home' %}">
			<img src="/static/img/favicon.ico" width="30" height="30" class="d-inline-block align-top">
			Book club
		</a>
		<form class="form-inline p-2" action="{% url 'books:search' %}">
    	<input class="form-control mr-sm-2" type="search" name="q">
    	<button class="btn my-2 my-sm-0 button-bg" type="submit"><i class="bi bi-search"></i></button>
  	</form>
		{% if request.user.is_authenticated %}
			<a href="{% url 'registration:logout' %}" class="navbar-brand p-2"><i class="bi bi-box-arrow-left"></i></a>
		{% else %}
			<a href="{% url 'registration:signin' %}" class="navbar-brand p-2"><i class="bi bi-person-circle"></i></a>
		{% endif %}
	</div>
</nav>

templates/included/paginator.html
<nav class="text-center">
  <ul class="pagination pagination-sm">
		{% if books.has_previous %}
			<li class="page-item"><a href="?page=1"><i class="bi bi-arrow-left"></i></a></li>
			<li class="page-item "><a class="page-link also-bg" href="?page={{ books.previous_page_number }}">&laquo; </a></li>
		{% endif %}
		<li class="page-item"><a class="page-link also-bg" href="?page={{ books.number }}">{{ books.number }}</a></li>
		{% if books.has_next %}
			<li class="page-item"><a class="page-link also-bg" href="?page={{ next_page_number }}">&raquo; </a></li>
		{% endif %}
  </ul>
</nav>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Book CLub</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
</head>
<body class="text-white also-bg">
	<!-- navbar -->
	{% include "included/navbar.html" %}
	<br>
	<br>
	
	<!-- main content -->
	<article class="container">
		{% block content %}
		{% endblock content %}
	</article>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
	</body>
</html>